#!/bin/bash

CONCERT_INGESTION_INSTANCE_ID="0000-0000-0000-0000"
DEMO_APP1_VERSION="1.0.0"
CONCERT_INGESTION_ENDPOINT="https://10.0.0.40:12443"
AUTH_HEADER="Authorization: $TOKEN"

NAME1="resilience assessment 1"
NAME2="resilience assessment 2"
NAME3="resilience assessment 3"
NAME4="resilience assessment 4"
NAME5="resilience assessment 5"
NAME6="resilience assessment 6"
NAME7="resilience assessment 7"
NAME8="resilience assessment 8"
NAME9="resilience assessment 9"
NAME10="Resil assessment 10"

PROFILE1="nfr_non_critical_apps_profile"
PROFILE2="nfr_non_critical_apps_profile"
PROFILE3="nfr_non_critical_apps_profile"
PROFILE4="nfr_non_critical_apps_profile"
PROFILE5="nfr_non_critical_apps_profile"
PROFILE6="nfr_non_critical_apps_profile"
PROFILE7="nfr_non_critical_apps_profile"
PROFILE8="nfr_non_critical_apps_profile"
PROFILE9="nfr_non_critical_apps_profile"
PROFILE10="nfr_non_critical_apps_profile"

TIMESTAMP1="2025-02-03T16:24:36.00Z"
TIMESTAMP2="2025-02-24T16:24:36.00Z"
TIMESTAMP3="2025-03-17T16:24:36.00Z"
TIMESTAMP4="2025-04-07T16:24:36.00Z"
TIMESTAMP5="2025-04-28T16:24:36.00Z"
TIMESTAMP6="2025-05-19T16:24:36.00Z"
TIMESTAMP7="2025-06-09T16:24:36.00Z"
TIMESTAMP8="2025-06-30T16:24:36.00Z"
TIMESTAMP9="2025-07-21T16:24:36.00Z"
TIMESTAMP10="2025-08-22T16:24:36.00Z"



curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME1"'",  
              "profile": "'"$PROFILE1"'",  
              "timestamp": "'"$TIMESTAMP1"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {                  
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",
                  "pct_availability_by_synthetic_tests": "100.00",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "99.99",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "6",
                  "mins_mttm_sev1": "6",
                  "mins_mttm_sev2": "6",
                  "mins_mttr_sev1": "3",
                  "mins_mttr_sev2": "3",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "2",
                  "mins_mttmitigate": "2",
                  "mins_mttmitigate_sev1": "2",
                  "mins_mttmitigate_sev2": "3",
                  "mins_rto": "3",
                  "pct_rto_tenant_validated": "98",
                  "mins_rpo": "3",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "95",

                  "ms_slo_latency": "20",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.7",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "2",
                  "mins_mtta": "2",
                  "mins_mtta_sev1": "3",
                  "mins_mtta_sev2": "3",
                  "mins_mttdiagnose": "2",
                  "mins_mttdiagnose_sev1": "2",
                  "mins_mttdiagnose_sev2": "2",

                  "mins_deployment_downtime": "1",
                  "pct_canary_release": "98",
                  "pct_sev1_incidents_by_change": "2",
                  "pct_sev2_incidents_by_change": "2",
                  "days_rca_sla_sev1": "3",
                  "days_rca_sla_sev2": "3",
                  "pct_runbook_coverage_sev1": "85",
                  "pct_runbook_coverage_sev2": "85",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "0",
                  "pct_dark_launch": "99",

                  "num_throughput_visits": "1200000",
                  "num_throughput_transactions": "1205000",
                  "freq_scaling_events_manual": "3",

                  "num_active_connection": "68",
                  "num_deprioritized_exposures": "98",
                  "num_disabled_unnecessary_services": "93",
                  "num_failed_login_attempts": "77",
                  "num_no_owner_files": "46",
                  "num_non_https_ports": "18",
                  "num_pending_update_across_hosts": "56",
                  "num_priority1_exposures": "70",
                  "num_priority2_exposures": "98",
                  "num_priority3_exposures": "29",
                  "num_suid_sgid_binaries": "33",
                  "num_unwanted_software_across_hosts": "54",
                  "num_world_writable_files": "47",
                  "pct_hosts_above_20pct_swap_space_utilization": "16",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "37",
                  "pct_hosts_above_90pct_var_log_usage": "65",
                  "pct_hosts_above_95pct_disk_usage": "13",
                  "pct_hosts_with_active_firewall": "84",
                  "pct_hosts_with_filesystem_errors": "99",
                  "pct_hosts_with_restricted_sudo_access": "78",
                  "pct_images_with_devel_pkgs": "95",
                  "pct_images_with_outdated_pkgs": "98",
                  "pct_images_with_unlicensed_pkgs": "25",
                  "pct_kernel_security_configurations": "65",
                  "pct_secure_server_status": "37",
                  "pct_workload_run_as_root": "40",
                  "pct_workloads_missing_cpu_limits": "2",
                  "pct_workloads_missing_cpu_requests": "31",
                  "pct_workloads_missing_memory_limits": "54",
                  "pct_workloads_missing_memory_requests": "33",
                  "pct_workloads_not_using_latest_image": "63",
                  "pct_workloads_with_capabilities_added": "100",
                  "pct_workloads_with_host_network": "17",
                  "pct_workloads_with_host_path_volumes": "75",
                  "pct_workloads_with_privileged_containers": "81",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME2"'",  
              "profile": "'"$PROFILE2"'",  
              "timestamp": "'"$TIMESTAMP2"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",
                  "pct_availability_by_synthetic_tests": "99.99",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "100.00",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "2",
                  "mins_mttm_sev1": "2",
                  "mins_mttm_sev2": "2",
                  "mins_mttr_sev1": "2",
                  "mins_mttr_sev2": "2",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "1",
                  "mins_mttmitigate": "1",
                  "mins_mttmitigate_sev1": "1",
                  "mins_mttmitigate_sev2": "1",
                  "mins_rto": "1",
                  "pct_rto_tenant_validated": "99",
                  "mins_rpo": "1",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "99",

                  "ms_slo_latency": "14",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "1",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "1",
                  "mins_mttdiagnose": "1",
                  "mins_mttdiagnose_sev1": "1",
                  "mins_mttdiagnose_sev2": "1",

                  "mins_deployment_downtime": "3",
                  "pct_canary_release": "99",
                  "pct_sev1_incidents_by_change": "4",
                  "pct_sev2_incidents_by_change": "4",
                  "days_rca_sla_sev1": "5",
                  "days_rca_sla_sev2": "5",
                  "pct_runbook_coverage_sev1": "95",
                  "pct_runbook_coverage_sev2": "95",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "2",
                  "pct_dark_launch": "94",

                  "num_throughput_visits": "3000000",
                  "num_throughput_transactions": "2800000",
                  "freq_scaling_events_manual": "1",
                  
                  "num_active_connection": "44",
                  "num_deprioritized_exposures": "71",
                  "num_disabled_unnecessary_services": "32",
                  "num_failed_login_attempts": "89",
                  "num_no_owner_files": "95",
                  "num_non_https_ports": "83",
                  "num_pending_update_across_hosts": "85",
                  "num_priority1_exposures": "53",
                  "num_priority2_exposures": "35",
                  "num_priority3_exposures": "13",
                  "num_suid_sgid_binaries": "67",
                  "num_unwanted_software_across_hosts": "45",
                  "num_world_writable_files": "64",
                  "pct_hosts_above_20pct_swap_space_utilization": "46",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "86",
                  "pct_hosts_above_90pct_var_log_usage": "44",
                  "pct_hosts_above_95pct_disk_usage": "16",
                  "pct_hosts_with_active_firewall": "17",
                  "pct_hosts_with_filesystem_errors": "35",
                  "pct_hosts_with_restricted_sudo_access": "73",
                  "pct_images_with_devel_pkgs": "8",
                  "pct_images_with_outdated_pkgs": "35",
                  "pct_images_with_unlicensed_pkgs": "62",
                  "pct_kernel_security_configurations": "64",
                  "pct_secure_server_status": "58",
                  "pct_workload_run_as_root": "71",
                  "pct_workloads_missing_cpu_limits": "74",
                  "pct_workloads_missing_cpu_requests": "8",
                  "pct_workloads_missing_memory_limits": "50",
                  "pct_workloads_missing_memory_requests": "82",
                  "pct_workloads_not_using_latest_image": "79",
                  "pct_workloads_with_capabilities_added": "21",
                  "pct_workloads_with_host_network": "73",
                  "pct_workloads_with_host_path_volumes": "95",
                  "pct_workloads_with_privileged_containers": "20",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'



curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME3"'",  
              "profile": "'"$PROFILE3"'",  
              "timestamp": "'"$TIMESTAMP3"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "100.00",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "99.99",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "15",
                  "mins_mttm_sev1": "15",
                  "mins_mttm_sev2": "15",
                  "mins_mttr_sev1": "5",
                  "mins_mttr_sev2": "5",
                  "mins_mttr_sev1_by_change": "5",
                  "mins_mttr_sev2_by_change": "5",
                  "mins_mttmitigate": "5",
                  "mins_mttmitigate_sev1": "5",
                  "mins_mttmitigate_sev2": "5",
                  "mins_rto": "5",
                  "pct_rto_tenant_validated": "95",
                  "mins_rpo": "6",
                  "pct_rpo_tenant_validated": "95",
                  "pct_rollback_coverage": "90",

                  "ms_slo_latency": "20",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "2",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "2",
                  "mins_mttdiagnose": "2",
                  "mins_mttdiagnose_sev1": "2",
                  "mins_mttdiagnose_sev2": "2",

                  "mins_deployment_downtime": "1",
                  "pct_canary_release": "98",
                  "pct_sev1_incidents_by_change": "2",
                  "pct_sev2_incidents_by_change": "2",
                  "days_rca_sla_sev1": "3",
                  "days_rca_sla_sev2": "3",
                  "pct_runbook_coverage_sev1": "85",
                  "pct_runbook_coverage_sev2": "85",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "0",
                  "pct_dark_launch": "99",

                  "num_throughput_visits": "1200000",
                  "num_throughput_transactions": "1205000",
                  "freq_scaling_events_manual": "3",
                                  
                  "num_active_connection": "70",
                  "num_deprioritized_exposures": "65",
                  "num_disabled_unnecessary_services": "18",
                  "num_failed_login_attempts": "56",
                  "num_no_owner_files": "28",
                  "num_non_https_ports": "45",
                  "num_pending_update_across_hosts": "59",
                  "num_priority1_exposures": "4",
                  "num_priority2_exposures": "11",
                  "num_priority3_exposures": "23",
                  "num_suid_sgid_binaries": "16",
                  "num_unwanted_software_across_hosts": "1",
                  "num_world_writable_files": "53",
                  "pct_hosts_above_20pct_swap_space_utilization": "29",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "34",
                  "pct_hosts_above_90pct_var_log_usage": "17",
                  "pct_hosts_above_95pct_disk_usage": "5",
                  "pct_hosts_with_active_firewall": "64",
                  "pct_hosts_with_filesystem_errors": "56",
                  "pct_hosts_with_restricted_sudo_access": "82",
                  "pct_images_with_devel_pkgs": "72",
                  "pct_images_with_outdated_pkgs": "28",
                  "pct_images_with_unlicensed_pkgs": "39",
                  "pct_kernel_security_configurations": "76",
                  "pct_secure_server_status": "44",
                  "pct_workload_run_as_root": "95",
                  "pct_workloads_missing_cpu_limits": "57",
                  "pct_workloads_missing_cpu_requests": "4",
                  "pct_workloads_missing_memory_limits": "83",
                  "pct_workloads_missing_memory_requests": "21",
                  "pct_workloads_not_using_latest_image": "32",
                  "pct_workloads_with_capabilities_added": "93",
                  "pct_workloads_with_host_network": "38",
                  "pct_workloads_with_host_path_volumes": "11",
                  "pct_workloads_with_privileged_containers": "30",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME4"'",  
              "profile": "'"$PROFILE4"'",  
              "timestamp": "'"$TIMESTAMP4"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "99.99",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "100.00",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "2",
                  "mins_mttm_sev1": "2",
                  "mins_mttm_sev2": "2",
                  "mins_mttr_sev1": "2",
                  "mins_mttr_sev2": "2",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "1",
                  "mins_mttmitigate": "1",
                  "mins_mttmitigate_sev1": "1",
                  "mins_mttmitigate_sev2": "1",
                  "mins_rto": "1",
                  "pct_rto_tenant_validated": "99",
                  "mins_rpo": "1",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "99",

                  "ms_slo_latency": "14",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "1",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "1",
                  "mins_mttdiagnose": "1",
                  "mins_mttdiagnose_sev1": "1",
                  "mins_mttdiagnose_sev2": "1",

                  "mins_deployment_downtime": "3",
                  "pct_canary_release": "99",
                  "pct_sev1_incidents_by_change": "4",
                  "pct_sev2_incidents_by_change": "4",
                  "days_rca_sla_sev1": "5",
                  "days_rca_sla_sev2": "5",
                  "pct_runbook_coverage_sev1": "95",
                  "pct_runbook_coverage_sev2": "95",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "2",
                  "pct_dark_launch": "94",

                  "num_throughput_visits": "3000000",
                  "num_throughput_transactions": "2800000",
                  "freq_scaling_events_manual": "1",
                                  
                  "num_active_connection": "79",
                  "num_deprioritized_exposures": "98",
                  "num_disabled_unnecessary_services": "88",
                  "num_failed_login_attempts": "57",
                  "num_no_owner_files": "53",
                  "num_non_https_ports": "44",
                  "num_pending_update_across_hosts": "4",
                  "num_priority1_exposures": "93",
                  "num_priority2_exposures": "16",
                  "num_priority3_exposures": "71",
                  "num_suid_sgid_binaries": "13",
                  "num_unwanted_software_across_hosts": "81",
                  "num_world_writable_files": "82",
                  "pct_hosts_above_20pct_swap_space_utilization": "40",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "77",
                  "pct_hosts_above_90pct_var_log_usage": "88",
                  "pct_hosts_above_95pct_disk_usage": "27",
                  "pct_hosts_with_active_firewall": "80",
                  "pct_hosts_with_filesystem_errors": "77",
                  "pct_hosts_with_restricted_sudo_access": "24",
                  "pct_images_with_devel_pkgs": "56",
                  "pct_images_with_outdated_pkgs": "77",
                  "pct_images_with_unlicensed_pkgs": "12",
                  "pct_kernel_security_configurations": "48",
                  "pct_secure_server_status": "88",
                  "pct_workload_run_as_root": "5",
                  "pct_workloads_missing_cpu_limits": "79",
                  "pct_workloads_missing_cpu_requests": "9",
                  "pct_workloads_missing_memory_limits": "73",
                  "pct_workloads_missing_memory_requests": "87",
                  "pct_workloads_not_using_latest_image": "31",
                  "pct_workloads_with_capabilities_added": "23",
                  "pct_workloads_with_host_network": "85",
                  "pct_workloads_with_host_path_volumes": "12",
                  "pct_workloads_with_privileged_containers": "4",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME5"'",  
              "profile": "'"$PROFILE5"'",  
              "timestamp": "'"$TIMESTAMP5"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "100.00",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "99.99",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "15",
                  "mins_mttm_sev1": "15",
                  "mins_mttm_sev2": "15",
                  "mins_mttr_sev1": "5",
                  "mins_mttr_sev2": "5",
                  "mins_mttr_sev1_by_change": "5",
                  "mins_mttr_sev2_by_change": "5",
                  "mins_mttmitigate": "5",
                  "mins_mttmitigate_sev1": "5",
                  "mins_mttmitigate_sev2": "5",
                  "mins_rto": "5",
                  "pct_rto_tenant_validated": "95",
                  "mins_rpo": "6",
                  "pct_rpo_tenant_validated": "95",
                  "pct_rollback_coverage": "90",

                  "ms_slo_latency": "20",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "2",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "2",
                  "mins_mttdiagnose": "2",
                  "mins_mttdiagnose_sev1": "2",
                  "mins_mttdiagnose_sev2": "2",

                  "mins_deployment_downtime": "1",
                  "pct_canary_release": "98",
                  "pct_sev1_incidents_by_change": "2",
                  "pct_sev2_incidents_by_change": "2",
                  "days_rca_sla_sev1": "3",
                  "days_rca_sla_sev2": "3",
                  "pct_runbook_coverage_sev1": "85",
                  "pct_runbook_coverage_sev2": "85",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "0",
                  "pct_dark_launch": "99",

                  "num_throughput_visits": "1200000",
                  "num_throughput_transactions": "1205000",
                  "freq_scaling_events_manual": "3",
                                  
                  "num_active_connection": "61",
                  "num_deprioritized_exposures": "41",
                  "num_disabled_unnecessary_services": "10",
                  "num_failed_login_attempts": "63",
                  "num_no_owner_files": "24",
                  "num_non_https_ports": "86",
                  "num_pending_update_across_hosts": "67",
                  "num_priority1_exposures": "25",
                  "num_priority2_exposures": "61",
                  "num_priority3_exposures": "51",
                  "num_suid_sgid_binaries": "25",
                  "num_unwanted_software_across_hosts": "20",
                  "num_world_writable_files": "55",
                  "pct_hosts_above_20pct_swap_space_utilization": "89",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "6",
                  "pct_hosts_above_90pct_var_log_usage": "23",
                  "pct_hosts_above_95pct_disk_usage": "83",
                  "pct_hosts_with_active_firewall": "3",
                  "pct_hosts_with_filesystem_errors": "79",
                  "pct_hosts_with_restricted_sudo_access": "52",
                  "pct_images_with_devel_pkgs": "20",
                  "pct_images_with_outdated_pkgs": "5",
                  "pct_images_with_unlicensed_pkgs": "55",
                  "pct_kernel_security_configurations": "75",
                  "pct_secure_server_status": "70",
                  "pct_workload_run_as_root": "28",
                  "pct_workloads_missing_cpu_limits": "55",
                  "pct_workloads_missing_cpu_requests": "66",
                  "pct_workloads_missing_memory_limits": "42",
                  "pct_workloads_missing_memory_requests": "40",
                  "pct_workloads_not_using_latest_image": "19",
                  "pct_workloads_with_capabilities_added": "55",
                  "pct_workloads_with_host_network": "60",
                  "pct_workloads_with_host_path_volumes": "89",
                  "pct_workloads_with_privileged_containers": "78",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME6"'",  
              "profile": "'"$PROFILE6"'",  
              "timestamp": "'"$TIMESTAMP6"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "100.00",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "99.99",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "6",
                  "mins_mttm_sev1": "6",
                  "mins_mttm_sev2": "6",
                  "mins_mttr_sev1": "3",
                  "mins_mttr_sev2": "3",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "2",
                  "mins_mttmitigate": "2",
                  "mins_mttmitigate_sev1": "2",
                  "mins_mttmitigate_sev2": "3",
                  "mins_rto": "3",
                  "pct_rto_tenant_validated": "98",
                  "mins_rpo": "3",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "95",

                  "ms_slo_latency": "20",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.7",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "2",
                  "mins_mtta": "2",
                  "mins_mtta_sev1": "3",
                  "mins_mtta_sev2": "3",
                  "mins_mttdiagnose": "2",
                  "mins_mttdiagnose_sev1": "2",
                  "mins_mttdiagnose_sev2": "2",

                  "mins_deployment_downtime": "1",
                  "pct_canary_release": "98",
                  "pct_sev1_incidents_by_change": "2",
                  "pct_sev2_incidents_by_change": "2",
                  "days_rca_sla_sev1": "3",
                  "days_rca_sla_sev2": "3",
                  "pct_runbook_coverage_sev1": "85",
                  "pct_runbook_coverage_sev2": "85",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "0",
                  "pct_dark_launch": "99",

                  "num_throughput_visits": "1200000",
                  "num_throughput_transactions": "1205000",
                  "freq_scaling_events_manual": "3",
                  
                  "num_active_connection": "54",
                  "num_deprioritized_exposures": "13",
                  "num_disabled_unnecessary_services": "25",
                  "num_failed_login_attempts": "66",
                  "num_no_owner_files": "26",
                  "num_non_https_ports": "43",
                  "num_pending_update_across_hosts": "21",
                  "num_priority1_exposures": "35",
                  "num_priority2_exposures": "65",
                  "num_priority3_exposures": "57",
                  "num_suid_sgid_binaries": "13",
                  "num_unwanted_software_across_hosts": "48",
                  "num_world_writable_files": "8",
                  "pct_hosts_above_20pct_swap_space_utilization": "97",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "66",
                  "pct_hosts_above_90pct_var_log_usage": "63",
                  "pct_hosts_above_95pct_disk_usage": "82",
                  "pct_hosts_with_active_firewall": "32",
                  "pct_hosts_with_filesystem_errors": "71",
                  "pct_hosts_with_restricted_sudo_access": "52",
                  "pct_images_with_devel_pkgs": "15",
                  "pct_images_with_outdated_pkgs": "58",
                  "pct_images_with_unlicensed_pkgs": "44",
                  "pct_kernel_security_configurations": "66",
                  "pct_secure_server_status": "93",
                  "pct_workload_run_as_root": "25",
                  "pct_workloads_missing_cpu_limits": "23",
                  "pct_workloads_missing_cpu_requests": "17",
                  "pct_workloads_missing_memory_limits": "32",
                  "pct_workloads_missing_memory_requests": "30",
                  "pct_workloads_not_using_latest_image": "31",
                  "pct_workloads_with_capabilities_added": "85",
                  "pct_workloads_with_host_network": "81",
                  "pct_workloads_with_host_path_volumes": "50",
                  "pct_workloads_with_privileged_containers": "57",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME7"'",  
              "profile": "'"$PROFILE7"'",  
              "timestamp": "'"$TIMESTAMP7"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "99.99",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "100.00",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "2",
                  "mins_mttm_sev1": "2",
                  "mins_mttm_sev2": "2",
                  "mins_mttr_sev1": "2",
                  "mins_mttr_sev2": "2",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "1",
                  "mins_mttmitigate": "1",
                  "mins_mttmitigate_sev1": "1",
                  "mins_mttmitigate_sev2": "1",
                  "mins_rto": "1",
                  "pct_rto_tenant_validated": "99",
                  "mins_rpo": "1",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "99",

                  "ms_slo_latency": "14",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "1",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "1",
                  "mins_mttdiagnose": "1",
                  "mins_mttdiagnose_sev1": "1",
                  "mins_mttdiagnose_sev2": "1",

                  "mins_deployment_downtime": "3",
                  "pct_canary_release": "99",
                  "pct_sev1_incidents_by_change": "4",
                  "pct_sev2_incidents_by_change": "4",
                  "days_rca_sla_sev1": "5",
                  "days_rca_sla_sev2": "5",
                  "pct_runbook_coverage_sev1": "95",
                  "pct_runbook_coverage_sev2": "95",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "2",
                  "pct_dark_launch": "94",

                  "num_throughput_visits": "3000000",
                  "num_throughput_transactions": "2800000",
                  "freq_scaling_events_manual": "1",
                                  
                  "num_active_connection": "85",
                  "num_deprioritized_exposures": "28",
                  "num_disabled_unnecessary_services": "21",
                  "num_failed_login_attempts": "17",
                  "num_no_owner_files": "37",
                  "num_non_https_ports": "36",
                  "num_pending_update_across_hosts": "46",
                  "num_priority1_exposures": "55",
                  "num_priority2_exposures": "94",
                  "num_priority3_exposures": "60",
                  "num_suid_sgid_binaries": "84",
                  "num_unwanted_software_across_hosts": "96",
                  "num_world_writable_files": "81",
                  "pct_hosts_above_20pct_swap_space_utilization": "59",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "11",
                  "pct_hosts_above_90pct_var_log_usage": "98",
                  "pct_hosts_above_95pct_disk_usage": "10",
                  "pct_hosts_with_active_firewall": "61",
                  "pct_hosts_with_filesystem_errors": "82",
                  "pct_hosts_with_restricted_sudo_access": "52",
                  "pct_images_with_devel_pkgs": "23",
                  "pct_images_with_outdated_pkgs": "66",
                  "pct_images_with_unlicensed_pkgs": "47",
                  "pct_kernel_security_configurations": "69",
                  "pct_secure_server_status": "31",
                  "pct_workload_run_as_root": "95",
                  "pct_workloads_missing_cpu_limits": "26",
                  "pct_workloads_missing_cpu_requests": "23",
                  "pct_workloads_missing_memory_limits": "41",
                  "pct_workloads_missing_memory_requests": "70",
                  "pct_workloads_not_using_latest_image": "25",
                  "pct_workloads_with_capabilities_added": "16",
                  "pct_workloads_with_host_network": "5",
                  "pct_workloads_with_host_path_volumes": "19",
                  "pct_workloads_with_privileged_containers": "62",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME8"'",  
              "profile": "'"$PROFILE8"'",  
              "timestamp": "'"$TIMESTAMP8"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "100.00",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "99.99",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "15",
                  "mins_mttm_sev1": "15",
                  "mins_mttm_sev2": "15",
                  "mins_mttr_sev1": "5",
                  "mins_mttr_sev2": "5",
                  "mins_mttr_sev1_by_change": "5",
                  "mins_mttr_sev2_by_change": "5",
                  "mins_mttmitigate": "5",
                  "mins_mttmitigate_sev1": "5",
                  "mins_mttmitigate_sev2": "5",
                  "mins_rto": "5",
                  "pct_rto_tenant_validated": "95",
                  "mins_rpo": "6",
                  "pct_rpo_tenant_validated": "95",
                  "pct_rollback_coverage": "90",

                  "ms_slo_latency": "20",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "2",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "2",
                  "mins_mttdiagnose": "2",
                  "mins_mttdiagnose_sev1": "2",
                  "mins_mttdiagnose_sev2": "2",

                  "mins_deployment_downtime": "1",
                  "pct_canary_release": "98",
                  "pct_sev1_incidents_by_change": "2",
                  "pct_sev2_incidents_by_change": "2",
                  "days_rca_sla_sev1": "3",
                  "days_rca_sla_sev2": "3",
                  "pct_runbook_coverage_sev1": "85",
                  "pct_runbook_coverage_sev2": "85",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "0",
                  "pct_dark_launch": "99",

                  "num_throughput_visits": "1200000",
                  "num_throughput_transactions": "1205000",
                  "freq_scaling_events_manual": "3",
                  
                  "num_active_connection": "85",
                  "num_deprioritized_exposures": "4",
                  "num_disabled_unnecessary_services": "73",
                  "num_failed_login_attempts": "79",
                  "num_no_owner_files": "37",
                  "num_non_https_ports": "84",
                  "num_pending_update_across_hosts": "75",
                  "num_priority1_exposures": "95",
                  "num_priority2_exposures": "62",
                  "num_priority3_exposures": "98",
                  "num_suid_sgid_binaries": "2",
                  "num_unwanted_software_across_hosts": "59",
                  "num_world_writable_files": "36",
                  "pct_hosts_above_20pct_swap_space_utilization": "52",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "89",
                  "pct_hosts_above_90pct_var_log_usage": "78",
                  "pct_hosts_above_95pct_disk_usage": "27",
                  "pct_hosts_with_active_firewall": "11",
                  "pct_hosts_with_filesystem_errors": "62",
                  "pct_hosts_with_restricted_sudo_access": "31",
                  "pct_images_with_devel_pkgs": "42",
                  "pct_images_with_outdated_pkgs": "86",
                  "pct_images_with_unlicensed_pkgs": "85",
                  "pct_kernel_security_configurations": "56",
                  "pct_secure_server_status": "87",
                  "pct_workload_run_as_root": "54",
                  "pct_workloads_missing_cpu_limits": "46",
                  "pct_workloads_missing_cpu_requests": "77",
                  "pct_workloads_missing_memory_limits": "54",
                  "pct_workloads_missing_memory_requests": "41",
                  "pct_workloads_not_using_latest_image": "2",
                  "pct_workloads_with_capabilities_added": "7",
                  "pct_workloads_with_host_network": "62",
                  "pct_workloads_with_host_path_volumes": "83",
                  "pct_workloads_with_privileged_containers": "28",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
            -H "$AUTH_HEADER" \
            -d '{
              "name": "'"$NAME9"'",  
              "profile": "'"$PROFILE9"'",  
              "timestamp": "'"$TIMESTAMP9"'",  
              "version": "'"$DEMO_APP1_VERSION"'", 
              "target_type": "app",
              "target": "qotd-app",
              "data": {                  
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                  "pct_availability_by_synthetic_tests": "99.99",
                  "pct_availability_by_error_rate": "100.00",
                  "pct_availability_by_downtime_post_rca": "100.00",
                  "pct_availability_by_region_by_synthetic_tests": "100.00",
                  "pct_availability_by_region_by_error_rate": "100.00",
                  "pct_availability_by_region_by_downtime_post_rca": "100.00",

                  "pct_data_replication": "90",
                  "pct_multi_zone_deployment": "92",
                  "pct_data_replication": "93",
                  "zone_distribution_pct": "90",
                  "recovery_time_sec": "2",
                  "redundancy_factor": "3",

                  "mins_mttm": "2",
                  "mins_mttm_sev1": "2",
                  "mins_mttm_sev2": "2",
                  "mins_mttr_sev1": "2",
                  "mins_mttr_sev2": "2",
                  "mins_mttr_sev1_by_change": "1",
                  "mins_mttr_sev2_by_change": "1",
                  "mins_mttmitigate": "1",
                  "mins_mttmitigate_sev1": "1",
                  "mins_mttmitigate_sev2": "1",
                  "mins_rto": "1",
                  "pct_rto_tenant_validated": "99",
                  "mins_rpo": "1",
                  "pct_rpo_tenant_validated": "99",
                  "pct_rollback_coverage": "99",

                  "ms_slo_latency": "14",
                  "pct_slo_latency_errorbudget": "100",
                  "txt_slo_latency_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_slo_error_rate": "0.4",
                  "pct_slo_error_rate_errorbudget": "100",
                  "txt_slo_error_rate_practice": "There is at least a monthly cadence on reviewing user experience outside what is specified in the SLO.  The insights drive adjustments to the SLO and process to maintain it.",
                  "pct_tenants_impacted_sev1": "1",
                  "pct_tenants_impacted_sev2": "1",

                  "pct_incidents_detected_by_monitoring": "100",
                  "pct_sev1_incidents_detected_by_monitoring": "100",
                  "pct_sev2_incidents_detected_by_monitoring": "100",
                  "mins_mttd": "1",
                  "mins_mttd_sev1": "1",
                  "mins_mttd_sev2": "1",
                  "mins_mtta": "1",
                  "mins_mtta_sev1": "1",
                  "mins_mtta_sev2": "1",
                  "mins_mttdiagnose": "1",
                  "mins_mttdiagnose_sev1": "1",
                  "mins_mttdiagnose_sev2": "1",

                  "mins_deployment_downtime": "3",
                  "pct_canary_release": "99",
                  "pct_sev1_incidents_by_change": "4",
                  "pct_sev2_incidents_by_change": "4",
                  "days_rca_sla_sev1": "5",
                  "days_rca_sla_sev2": "5",
                  "pct_runbook_coverage_sev1": "95",
                  "pct_runbook_coverage_sev2": "95",
                  "pct_automation_coverage": "95",
                  "pct_automation_coverage_change": "99",
                  "pct_automation_coverage_deployment": "99",
                  "num_human_touch_per_change": "2",
                  "pct_dark_launch": "94",

                  "num_throughput_visits": "3000000",
                  "num_throughput_transactions": "2800000",
                  "freq_scaling_events_manual": "1",
                  
                  "num_active_connection": "52",
                  "num_deprioritized_exposures": "22",
                  "num_disabled_unnecessary_services": "66",
                  "num_failed_login_attempts": "44",
                  "num_no_owner_files": "8",
                  "num_non_https_ports": "67",
                  "num_pending_update_across_hosts": "92",
                  "num_priority1_exposures": "13",
                  "num_priority2_exposures": "67",
                  "num_priority3_exposures": "44",
                  "num_suid_sgid_binaries": "84",
                  "num_unwanted_software_across_hosts": "63",
                  "num_world_writable_files": "78",
                  "pct_hosts_above_20pct_swap_space_utilization": "32",
                  "pct_hosts_above_70pct_tmp_disk_space_utilization": "47",
                  "pct_hosts_above_90pct_var_log_usage": "21",
                  "pct_hosts_above_95pct_disk_usage": "66",
                  "pct_hosts_with_active_firewall": "89",
                  "pct_hosts_with_filesystem_errors": "19",
                  "pct_hosts_with_restricted_sudo_access": "53",
                  "pct_images_with_devel_pkgs": "41",
                  "pct_images_with_outdated_pkgs": "96",
                  "pct_images_with_unlicensed_pkgs": "46",
                  "pct_kernel_security_configurations": "4",
                  "pct_secure_server_status": "94",
                  "pct_workload_run_as_root": "29",
                  "pct_workloads_missing_cpu_limits": "30",
                  "pct_workloads_missing_cpu_requests": "82",
                  "pct_workloads_missing_memory_limits": "2",
                  "pct_workloads_missing_memory_requests": "39",
                  "pct_workloads_not_using_latest_image": "16",
                  "pct_workloads_with_capabilities_added": "32",
                  "pct_workloads_with_host_network": "80",
                  "pct_workloads_with_host_path_volumes": "35",
                  "pct_workloads_with_privileged_containers": "94",
                  "pct_images_latest_tag_identification": "42",
                  "pct_containers_missing_restart_policy": "23",
                  "pct_images_with_incorrect_logging_config": "51",
                  "pct_containers_missing_cpu_limit": "36",
                  "pct_containers_missing_memory_limit": "87",
                  "pct_images_with_incorrect_base_image": "55",
                  "pct_workloads_within_90pct_memory_limits": "40",
                  "pct_workloads_within_90pct_cpu_limits": "7",
                  "pct_images_with_layers_gt_20": "45",
                  "pct_layer_efficiency": "72",
                  "pct_image_provenance": "56",
                  "pct_minimal_attack_surface": "1",
                  "pct_immutable_infra": "20",
                  "avg_num_replicas_per_worker": "54",
                  "avg_msecs_health_check_latency": "9",
                  "pct_self_healing_success_actual": "89",
                  "pct_heavy_images": "58",
                  "parallelization_factor": "42",
                  "num_outdated_dependencies": "91",
                  "pct_pod_with_antiafinity": "86",
                  "pct_multi_node_deployment": "8"
              }
            }'


curl -k -X POST "${CONCERT_INGESTION_ENDPOINT}/resilience/grader/api/v1/evaluate" \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "InstanceID: $CONCERT_INGESTION_INSTANCE_ID" \
          -H "$AUTH_HEADER" \
          -d '{
            "name": "'"$NAME10"'",  
            "profile": "'"$PROFILE10"'",  
            "timestamp": "'"$TIMESTAMP10"'",  
            "version": "'"$DEMO_APP1_VERSION"'", 
            "target_type": "app",
            "target": "qotd-app",
            "data": {
                  "average_number_image_layers": "200",
                  "avg_image_size_mb": "57",
                  "max_image_size_mb": "951",
                  "max_number_image_layers": "711",
                  "num_deprioritized_vulnerabilities": "6",
                  "num_env_specific_configs": "59",
                  "num_hardcoded_secret": "25",
                  "num_priority1_vulnerabilities": "78",
                  "num_priority2_vulnerabilities": "55",
                  "num_priority3_vulnerabilities": "14",
                  "pct_containers_running_as_root": "71",
                  "pct_containers_using_custom_network": "86",
                  "pct_pods_with_readiness_probe_defined": "68",
                  "pct_policies_using_ingress_and_ports": "79",
                  "pct_policies_using_ipBlocks": "67",
                  "pct_policies_with_non_empty_rules": "56",
                  "pct_privileged_mode_containers": "51",
                  "pct_workload_liveness_initial_delay_defined": "59",
                  "pct_workload_network_policy_defined": "71",
                  "pct_workloads_service_account_defined": "58",

                "pct_availability_by_synthetic_tests": "99.5",
                "pct_availability_by_error_rate": "99.7",
                "pct_availability_by_downtime_post_rca": "99.6",
                "pct_availability_by_region_by_synthetic_tests": "99.5",
                "pct_availability_by_region_by_error_rate": "99.3",
                "pct_availability_by_region_by_downtime_post_rca": "99.5",

                "pct_data_replication": "10",
                "pct_multi_zone_deployment": "12",
		"pct_data_replication": "13",
                "zone_distribution_pct": "10",
                "recovery_time_sec": "2",
                "redundancy_factor": "1",

                "mins_mttm": "3",
                "mins_mttm_sev1": "4",
                "mins_mttm_sev2": "3",
                "mins_mttr_sev1": "5",
                "mins_mttr_sev2": "5",
                "mins_mttr_sev1_by_change": "5",
                "mins_mttr_sev2_by_change": "5",
                "mins_mttmitigate": "5",
                "mins_mttmitigate_sev1": "5",
                "mins_mttmitigate_sev2": "5",
                "mins_rto": "5",
                "pct_rto_tenant_validated": "95",
                "mins_rpo": "6",
                "pct_rpo_tenant_validated": "95",
                "pct_rollback_coverage": "90",

                "ms_slo_latency": "4500",
                "pct_slo_latency_errorbudget": "95",
                "txt_slo_latency_practice": "There is no structured review of user latency experience. Latency issues are handled only after user complaints become frequent.",
                "pct_slo_error_rate": "27.3",
                "pct_slo_error_rate_errorbudget": "99",
                "txt_slo_error_rate_practice": "No review process exists. Teams are unaware of error rate thresholds until critical issues arise.",
                "pct_tenants_impacted_sev1": "15",
                "pct_tenants_impacted_sev2": "18",

                "pct_incidents_detected_by_monitoring": "42",
                "pct_sev1_incidents_detected_by_monitoring": "39",
                "pct_sev2_incidents_detected_by_monitoring": "41",
                "mins_mttd": "15",
                "mins_mttd_sev1": "17",
                "mins_mttd_sev2": "20",
                "mins_mtta": "18",
                "mins_mtta_sev1": "20",
                "mins_mtta_sev2": "22",
                "mins_mttdiagnose": "25",
                "mins_mttdiagnose_sev1": "27",
                "mins_mttdiagnose_sev2": "30",

                "mins_deployment_downtime": "5",
                "pct_canary_release": "95",
                "pct_sev1_incidents_by_change": "4",
                "pct_sev2_incidents_by_change": "4",
                "days_rca_sla_sev1": "4",
                "days_rca_sla_sev2": "4",
                "pct_runbook_coverage_sev1": "95",
                "pct_runbook_coverage_sev2": "95",
                "pct_automation_coverage": "95",
                "pct_automation_coverage_change": "95",
                "pct_automation_coverage_deployment": "95",
                "num_human_touch_per_change": "0",
                "pct_dark_launch": "95",

                "num_throughput_visits": "1000001",
                "num_throughput_transactions": "900000",
                "freq_scaling_events_manual": "3",
                  
                "num_active_connection": "41",
                "num_deprioritized_exposures": "32",
                "num_disabled_unnecessary_services": "21",
                "num_failed_login_attempts": "46",
                "num_no_owner_files": "52",
                "num_non_https_ports": "78",
                "num_pending_update_across_hosts": "45",
                "num_priority1_exposures": "4",
                "num_priority2_exposures": "96",
                "num_priority3_exposures": "18",
                "num_suid_sgid_binaries": "53",
                "num_unwanted_software_across_hosts": "40",
                "num_world_writable_files": "50",
                "pct_hosts_above_20pct_swap_space_utilization": "88",
                "pct_hosts_above_70pct_tmp_disk_space_utilization": "67",
                "pct_hosts_above_90pct_var_log_usage": "42",
                "pct_hosts_above_95pct_disk_usage": "14",
                "pct_hosts_with_active_firewall": "50",
                "pct_hosts_with_filesystem_errors": "45",
                "pct_hosts_with_restricted_sudo_access": "63",
                "pct_images_with_devel_pkgs": "61",
                "pct_images_with_outdated_pkgs": "39",
                "pct_images_with_unlicensed_pkgs": "29",
                "pct_kernel_security_configurations": "68",
                "pct_secure_server_status": "49",
                "pct_workload_run_as_root": "33",
                "pct_workloads_missing_cpu_limits": "27",
                "pct_workloads_missing_cpu_requests": "49",
                "pct_workloads_missing_memory_limits": "26",
                "pct_workloads_missing_memory_requests": "47",
                "pct_workloads_not_using_latest_image": "94",
                "pct_workloads_with_capabilities_added": "57",
                "pct_workloads_with_host_network": "46",
                "pct_workloads_with_host_path_volumes": "91",
                "pct_workloads_with_privileged_containers": "38",
                "pct_images_latest_tag_identification": "42",
                "pct_containers_missing_restart_policy": "23",
                "pct_images_with_incorrect_logging_config": "51",
                "pct_containers_missing_cpu_limit": "36",
                "pct_containers_missing_memory_limit": "87",
                "pct_images_with_incorrect_base_image": "55",
                "pct_workloads_within_90pct_memory_limits": "40",
                "pct_workloads_within_90pct_cpu_limits": "7",
                "pct_images_with_layers_gt_20": "45",
                "pct_layer_efficiency": "72",
                "pct_image_provenance": "56",
                "pct_minimal_attack_surface": "1",
                "pct_immutable_infra": "20",
                "avg_num_replicas_per_worker": "54",
                "avg_msecs_health_check_latency": "9",
                "pct_self_healing_success_actual": "89",
                "pct_heavy_images": "58",
                "parallelization_factor": "42",
                "num_outdated_dependencies": "91",
                "pct_pod_with_antiafinity": "86",
                "pct_multi_node_deployment": "8"
            }
          }'
